
[Waves]
	#Default 2500
	"Sets points required to enter wave 1" = 2500
	#Default 12500
	"Sets points required to enter wave 2" = 12500
	#Default 100000
	"Sets points required to enter wave 3" = 100000
	#Default 1000000
	"Sets points required to enter wave 4" = 1000000
	#Default 2500000
	"Sets points required to enter wave 5" = 2500000
	#Default 7500000
	"Sets points required to enter wave 6" = 7500000

["Device Points"]
	#Default 1000
	"Sets points that will be added / subtracted by the devices" = 1000

["Base Form Equipment"]
	#Items / chance of spawning with it
	"Main Hand Slot for the PLAYER FORM ONLY" = ["minecraft:crossbow|60", "minecraft:flint_and_steel|20", "minecraft:ender_pearl|15", "minecraft:spyglass|15", "minecraft:totem_of_undying|10"]
	"Head Slot" = ["minecraft:chainmail_helmet|10", "minecraft:iron_helmet|40", "minecraft:leather_helmet|30", "minecraft:golden_helmet|15", "minecraft:diamond_helmet|5", "minecraft:netherite_helmet|2"]
	"Chest Slot" = ["minecraft:chainmail_chestplate|50", "minecraft:iron_chestplate|20", "minecraft:leather_chestplate|20", "minecraft:golden_chestplate|15", "minecraft:diamond_chestplate|5", "minecraft:netherite_chestplate|2"]
	"Legs Slot" = ["minecraft:leather_leggings|50", "minecraft:iron_leggings|20", "minecraft:chainmail_leggings|20", "minecraft:golden_leggings|15", "minecraft:diamond_leggings|5", "minecraft:netherite_leggings|2"]
	"Boots Slot" = ["minecraft:leather_boots|50", "minecraft:iron_boots|20", "minecraft:chainmail_boots|20", "minecraft:golden_boots|15", "minecraft:diamond_boots|5", "minecraft:netherite_boots|2"]
	#Default 300
	"Chance of the zombies spawning with improved equipment, the bigger the number the smaller the chance" = 300

